# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07a7e60e7094bea3b0348399fa2bd68dafa143246b75b5ca1ae11eb66da3ef360c7e728bd46bb025b561fb6950956c46126eff07a8c9390be1a28e40083b98e8

test:
  secret_key_base: 951d9bbc1d580e97029df4148eac3ce71edb3ba33df96cd81b986a8102223db45d5e1c149b07632ec25456b4f6a06cc332bab70c3f659dc20f500b8fbeaeb660

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
